import { User } from '../../../../domain';

export const user: User = {
  id: 123345,
  resource_url: 'https://api.discogs.com/users/murdrejg',
  uri: 'https://www.discogs.com/user/murdrejg',
  username: 'murdrejg',
  name: '',
  home_page: '',
  location: '',
  profile: '',
  registered: new Date(),
  rank: 0.0,
  num_pending: 0,
  num_for_sale: 0,
  num_lists: 0,
  releases_contributed: 0,
  releases_rated: 0,
  rating_avg: 0.0,
  inventory_url: 'https://api.discogs.com/users/murdrejg/inventory',
  collection_folders_url: 'https://api.discogs.com/users/murdrejg/collection/folders',
  collection_fields_url: 'https://api.discogs.com/users/murdrejg/collection/fields',
  wantlist_url: 'https://api.discogs.com/users/murdrejg/wants',
  avatar_url:
    'https://i.discogs.com/WIDgPGeQktN_J2BdYz69r35lPt-PBhOfLPfzwwOMYXM/rs:fill/g:sm/q:40/h:500/w:500/czM6Ly9kaXNjb2dz/LXVzZXItYXZhdGFy/cy9VLTM4OTM0NTYt/MTQ3Mzg0MDk4Ni5q/cGVn.jpeg',
  curr_abbr: 'SEK',
  activated: true,
  marketplace_suspended: false,
  banner_url: '',
  buyer_rating: 0.0,
  buyer_rating_stars: 0.0,
  buyer_num_ratings: 0,
  seller_rating: 0.0,
  seller_rating_stars: 0.0,
  seller_num_ratings: 0,
  is_staff: false,
  num_collection: 3,
  num_wantlist: 23,
  email: 'murdrejg@gmail.com',
  num_unread: 11,
};
